### ISSUE TITLE
APK crash in device.

### ISSUE THREAD

**Issue by higunjan** [obastemur/jxcore-android-basics#5]
I developed APK as per your instructed in GIT. I fixed bug which I face while development. I'm using `Android studio 2.3.0 and JAVA jdk 1.8`.
Now, APK generated successfully but while open these app it's crash doesn't open in my Device I checked with Android OS 4.0 to 6.0.
Let me know Why these happen & any other-way to Implement this thing. 
like I create build `exe for window` and `executable for Linux` using `jx-core`.

**Comment by obastemur** [comment]
@higunjan I no longer main this sample hence hard to say what's wrong there. any crash log?

**Comment by higunjan** [comment]
Yes crash log I have. As follow

>  E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.nubisa.jxcore, PID: 21965
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.nubisa.jxcore-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libjxcore.so"
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                       at java.lang.System.loadLibrary(System.java:988)
                                                       at com.nubisa.jxcore.jxcore.<clinit>(jxcore.java:13)
                                                       at com.nubisa.jxcore.MainActivity.onCreate(MainActivity.java:100)
                                                       at android.app.Activity.performCreate(Activity.java:5990)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
